# version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: