services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-backend
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate

    ports:
      - "5000:3000"   # host:container

    depends_on:
      - ollama

    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped

    volumes:
      - ollama_data:/root/.ollama

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: